# Generated by Django 4.1.7 on 2023-12-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BODEGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('cantidadespacio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecliente', models.CharField(max_length=50)),
                ('direccioncli', models.CharField(max_length=50)),
                ('telefonocli', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='COMPRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COMUNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecomuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='COURRIER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecourrier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EMPLEADO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutempleado', models.CharField(max_length=14)),
                ('rutdv', models.CharField(max_length=1)),
                ('nombreempleado', models.CharField(max_length=50)),
                ('apellidoempleado', models.CharField(max_length=50)),
                ('fechacontrato', models.DateField()),
                ('sueldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ESPACIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='REGION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_EMPLEADO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TIPOEMISION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoemision', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VENTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='VENTA_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.producto')),
                ('id_tipoemision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipoemision')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.venta')),
            ],
        ),
        migrations.CreateModel(
            name='SUCURSAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='PROVINCIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.region')),
            ],
        ),
        migrations.CreateModel(
            name='PROVEEDOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproveedor', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.proveedor'),
        ),
        migrations.CreateModel(
            name='GUIA_DESPACHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('detalle', models.CharField(max_length=50)),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.bodega')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.producto')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.tipo_empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.usuario'),
        ),
        migrations.CreateModel(
            name='DESPACHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcciondespacho', models.CharField(max_length=50)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.cliente')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna')),
                ('id_courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.courrier')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.venta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.provincia'),
        ),
        migrations.CreateModel(
            name='COMPRA_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.compra')),
                ('id_guiadp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.guia_despacho')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.empleado'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.usuario'),
        ),
        migrations.CreateModel(
            name='BODEGA_DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.espacios')),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.bodega')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.producto')),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna'),
        ),
    ]
