# Generated by Django 4.1.7 on 2024-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_empresa_remove_bodega_detalle_espacio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contrasenaEMP',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='rutEmpresa',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
