# Generated by Django 4.1.7 on 2024-09-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_empresa_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANUNCIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('modalidad', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=200)),
                ('remunerado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.empresa')),
            ],
        ),
    ]
