# Generated by Django 5.1.1 on 2024-11-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_tag_alter_estudiante_cv_estudiante_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='habilidades',
            field=models.ManyToManyField(blank=True, limit_choices_to=5, related_name='estudiantes', to='usuarios.tag'),
        ),
    ]
