# Generated by Django 5.1.1 on 2024-11-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='habilidades',
            field=models.ManyToManyField(blank=True, limit_choices_to=10, related_name='estudiantes', to='usuarios.tag'),
        ),
    ]
