# Generated by Django 5.1.1 on 2024-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_estudiante_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresa/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Una breve descripción sobre la empresa (máx. 1000 caracteres).', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
