# Generated by Django 5.1.1 on 2024-10-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anunciopractica',
            name='direccion',
        ),
        migrations.AddField(
            model_name='anunciopractica',
            name='ubicacion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
