# Generated by Django 5.1.1 on 2024-10-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuPractica', '0003_sector'),
        ('usuarios', '0004_empresa_descripcion_empresa_pagina_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuPractica.sector'),
        ),
    ]
