# Generated by Django 5.1.1 on 2024-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_uid_usuario_groups_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
