# Generated by Django 5.1.1 on 2024-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_remove_anunciopractica_requisitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('En revisión', 'En revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En revisión', max_length=20),
        ),
    ]
